### PR TITLE
Add Prismic preview support

### PR DESCRIPTION
**Pull request by ellsclytn**
Also switches to Prismic Utils based fetching (delete all the things!)

### CODE REVIEW

**Comment by danhenderson** [comment]
How come design has been split out into it's own reducer?

**Comment by ellsclytn** [comment]
@danhenderson just because design has its own bit of magic happening regarding fonts, and so the default deserialization that Prismic Utils provides wouldn't have cut it. Having its own place in the store seemed like a neater approach due to that.

**Comment by danhenderson** [comment]
Ah yep, I see now. The other possibility would be to pass `createDocumentReducer` a custom handler e.g.

```
createDocumentReducer('page', {
 fetchSuccess: theOldFetchSuccessHere
})
```

**Comment by ellsclytn** [comment]
Yeah, did think about that, but overall I think I liked having design as its own object in the store more than being some nested object, and this results in a little more deleted code vs. keeping the old fetch success handler.

**Comment by danhenderson** [comment]
Sounds good to me. I personally prefer altering the `fetchSuccess` handler, but as long as it has been considered, that is all good. Neither way is wrong or anything like that.

**Pull request merged**
